name: DevOps Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Project
        run: echo "Build Successful"

      - name: Deploy
        run: echo "Deployment Successful"
